### ISSUE TITLE
Bug in offer view title

### ISSUE THREAD

**Issue by lam3lka** [michalmikolajczyk/viking-garage-frontend#197]
This problem appears only in longer titles of motorcycle (3 lines)
https://www.vikinggarage.com/offer/4/honda-supersound-125-1998-warsaw-poland 

<img width="360" alt="zrzut ekranu 2017-09-02 o 13 39 31" src="https://user-images.githubusercontent.com/28931514/29995216-8ea26db8-8fe4-11e7-8114-22393af3602a.png">

**Comment by lam3lka** [comment]
Michał halo

**Comment by michalmikolajczyk** [comment]
this one was solved with and is now merged to #209

**Comment by lam3lka** [comment]
ok, we can close it

**Comment by michalmikolajczyk** [comment]
@lam3lka please close

**Comment by lam3lka** [comment]
It is not ready to be closed. I checked more offers and bug is still there. 
<img width="945" alt="zrzut ekranu 2018-03-13 o 17 41 51" src="https://user-images.githubusercontent.com/28931514/37356265-d978030a-26e5-11e8-88a3-53d6ed0544e1.png">
